---
# The production version of docker-cloud-test should be the image that includes the website with
# your topic subpage.  This version of the website should be available on port 8081 of your server.
- name: Deploy the staging version of your website based on the newest tag of your docker-cloud-test image
  hosts: localhost
  become: true
  vars:
    final_web_environment: staging
    final_web_image_version: release-0.6.0
    final_web_host_port: 8081
    final_web_container_port: 5000
  roles:
    - final_web
  
